import type { SupportedLanguage } from "@/i18n/config"

export type PricingCurrency = "USD" | "CNY"
export type ModelAvailabilityStatus = "available" | "coming-soon" | "legacy-mapped"

export interface PricingProvider {
  id: string
  name: string
  sourceLabel: string
  sourceLabelEn: string
  sourceUrl: string
  sourceNote: string
  sourceNoteEn: string
}

export interface ModelPricing {
  id: string
  providerId: string
  name: string
  description: string
  descriptionEn: string
  currency: PricingCurrency
  inputCostPer1mToken: number
  outputCostPer1mToken: number
  cacheReadCostPer1mToken?: number
  cacheWriteCostPer1mToken?: number
  pricingContext?: string
  pricingContextEn?: string
  pricingNote?: string
  pricingNoteEn?: string
  sourceLabel: string
  sourceLabelEn: string
  sourceUrl: string
  sourceNote: string
  sourceNoteEn: string
  sourceSyncedAt: string
  availabilityStatus: ModelAvailabilityStatus
  legacyIds?: string[]
  modelsDevId?: string
}

export interface PricingData {
  providers: PricingProvider[]
  models: ModelPricing[]
  inputOutputRatio: number
  exchangeRateUsdToCny: number
  updatedAt: string
  catalogRefreshDate: string
  source: string
  sourceEn: string
}

const VERIFIED_AT = "2026-09-26"

const providers: PricingProvider[] = [
  {
    id: "openai",
    name: "OpenAI",
    sourceLabel: "OpenAI API Pricing",
    sourceLabelEn: "OpenAI API Pricing",
    sourceUrl: "https://developers.openai.com/api/docs/pricing#latest-models",
    sourceNote: "使用 OpenAI 第一方 API 标准档位；Batch、Flex、Fast 和区域处理附加费未计入。Token 估算使用已选档位的输入/输出价格，缓存读写价单独披露。文档不保证特定账户或地区的访问权限。",
    sourceNoteEn: "Uses OpenAI first-party API standard rates; Batch, Flex, Fast, and regional processing uplifts are excluded. Token estimates use the selected tier's input/output rates; cache rates are disclosed separately. Documentation does not confirm access for a specific account or region.",
  },
  {
    id: "anthropic",
    name: "Anthropic Claude",
    sourceLabel: "Anthropic Claude Pricing",
    sourceLabelEn: "Anthropic Claude Pricing",
    sourceUrl: "https://platform.claude.com/docs/en/about-claude/pricing#model-pricing",
    sourceNote: "使用 Anthropic 第一方 Claude API 标准档位；云市场平台可能采用不同价格。Token 估算使用已选档位的输入/输出价格，缓存读写价单独披露。文档不保证特定账户访问权限。",
    sourceNoteEn: "Uses Anthropic first-party Claude API standard rates; cloud marketplace platforms may differ. Token estimates use the selected tier's input/output rates; cache rates are disclosed separately. Documentation does not confirm account access.",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    sourceLabel: "DeepSeek Models & Pricing",
    sourceLabelEn: "DeepSeek Models & Pricing",
    sourceUrl: "https://api-docs.deepseek.com/quick_start/pricing/",
    sourceNote: "缓存命中非保证；峰值时段按官方 UTC 时间表区分。Token 估算使用已选档位的输入/输出价格，缓存读写价单独披露。文档不保证特定账户访问权限。",
    sourceNoteEn: "Cache hits are not guaranteed; peak rates follow the provider's UTC schedule. Token estimates use the selected tier's input/output rates; cache rates are disclosed separately. Documentation does not confirm account access.",
  },
  {
    id: "glm",
    name: "智谱 GLM",
    sourceLabel: "智谱开放平台 API 定价",
    sourceLabelEn: "BigModel API Pricing (China)",
    sourceUrl: "https://docs.bigmodel.cn/cn/guide/start/pricing.md",
    sourceNote: "仅使用中国 BigModel 平台人民币价格，不适用于国际 Z.AI；缓存存储标注为限时免费。Token 估算使用已选档位的输入/输出价格，缓存读写价单独披露。文档不保证特定账户访问权限。",
    sourceNoteEn: "Uses Chinese BigModel CNY rates, not international Z.AI pricing; cache storage is marked temporarily free. Token estimates use the selected tier's input/output rates; cache rates are disclosed separately. Documentation does not confirm account access.",
  },
  {
    id: "minimax",
    name: "MiniMax",
    sourceLabel: "MiniMax Pay-as-you-go Pricing",
    sourceLabelEn: "MiniMax Pay-as-you-go Pricing",
    sourceUrl: "https://platform.minimax.io/docs/guides/pricing-paygo.md",
    sourceNote: "使用公开的标准 PAYG 档位；优先级服务另计。Token 估算使用已选档位的输入/输出价格，缓存读写价单独披露。文档不保证特定账户访问权限。",
    sourceNoteEn: "Uses the published standard PAYG tier; priority service is separate. Token estimates use the selected tier's input/output rates; cache rates are disclosed separately. Documentation does not confirm account access.",
  },
]

type ModelDefinition = Omit<
  ModelPricing,
  "sourceLabel" | "sourceLabelEn" | "sourceNote" | "sourceNoteEn" | "sourceSyncedAt"
>

function createModel(model: ModelDefinition): ModelPricing {
  const provider = providers.find((item) => item.id === model.providerId)
  if (!provider) {
    throw new Error(`Unknown pricing provider: ${model.providerId}`)
  }

  return {
    ...model,
    sourceLabel: provider.sourceLabel,
    sourceLabelEn: provider.sourceLabelEn,
    sourceNote: provider.sourceNote,
    sourceNoteEn: provider.sourceNoteEn,
    sourceSyncedAt: VERIFIED_AT,
  }
}

const openAiPricingUrl = "https://developers.openai.com/api/docs/pricing#latest-models"
const anthropicPricingUrl = "https://platform.claude.com/docs/en/about-claude/pricing#model-pricing"
const deepSeekPricingUrl = "https://api-docs.deepseek.com/quick_start/pricing/"
const bigModelPricingUrl = "https://docs.bigmodel.cn/cn/guide/start/pricing.md"
const bigModelOverviewUrl = "https://docs.bigmodel.cn/cn/guide/start/model-overview.md"
const miniMaxPricingUrl = "https://platform.minimax.io/docs/guides/pricing-paygo.md"

export const pricingData: PricingData = {
  updatedAt: VERIFIED_AT,
  catalogRefreshDate: VERIFIED_AT,
  source: "第一方服务商定价文档静态快照（复核日期：2026-09-26）",
  sourceEn: "Static snapshot from first-party provider pricing documents (checked 2026-09-26)",
  inputOutputRatio: 3,
  exchangeRateUsdToCny: 7.25,
  providers,
  models: [
    createModel({
      id: "gpt-6-astra",
      providerId: "openai",
      name: "GPT-6 Astra",
      description: "旗舰复杂推理与端到端任务",
      descriptionEn: "Flagship model for complex reasoning and end-to-end work",
      currency: "USD",
      inputCostPer1mToken: 10,
      outputCostPer1mToken: 50,
      cacheReadCostPer1mToken: 1,
      cacheWriteCostPer1mToken: 12.5,
      pricingContext: "标准档；输入不超过 272K tokens",
      pricingContextEn: "Standard tier; up to 272K input tokens",
      pricingNote: "同一请求输入超过 272K 时，整次请求适用单列的长上下文档：输入 $20、输出 $75、缓存读 $2、写 $25。",
      pricingNoteEn: "Requests with more than 272K input tokens use the separately listed full-request long-context tier: $20 input, $75 output, $2 cache read, and $25 cache write.",
      sourceUrl: "https://developers.openai.com/api/docs/models/gpt-6-astra",
      availabilityStatus: "available",
    }),
    createModel({
      id: "gpt-6-astra-long-context",
      providerId: "openai",
      name: "GPT-6 Astra · >272K input",
      description: "长上下文请求完整计价档",
      descriptionEn: "Full-request long-context pricing tier",
      currency: "USD",
      inputCostPer1mToken: 20,
      outputCostPer1mToken: 75,
      cacheReadCostPer1mToken: 2,
      cacheWriteCostPer1mToken: 25,
      pricingContext: "输入超过 272K tokens 时适用于整次请求",
      pricingContextEn: "Applies to the full request when input exceeds 272K tokens",
      pricingNote: "官方模型页明确为超过 272K 输入 token 的请求应用 2 倍输入/缓存与 1.5 倍输出价格。",
      pricingNoteEn: "The official model page applies 2x input/cache and 1.5x output rates to requests with more than 272K input tokens.",
      sourceUrl: "https://developers.openai.com/api/docs/models/gpt-6-astra",
      availabilityStatus: "available",
    }),
    createModel({
      id: "gpt-6-sol",
      providerId: "openai",
      name: "GPT-6 Sol",
      description: "复杂编程与智能体工作流",
      descriptionEn: "Complex coding and agentic workflows",
      currency: "USD",
      inputCostPer1mToken: 2,
      outputCostPer1mToken: 10,
      cacheReadCostPer1mToken: 0.2,
      cacheWriteCostPer1mToken: 2.5,
      pricingContext: "标准档；输入不超过 272K tokens",
      pricingContextEn: "Standard tier; up to 272K input tokens",
      pricingNote: "输入超过 272K 时适用单列的整次请求长上下文价格：输入 $4、输出 $15、缓存读 $0.40、写 $5。",
      pricingNoteEn: "Over 272K input uses the separately listed full-request long-context rates: $4 input, $15 output, $0.40 cache read, and $5 cache write.",
      sourceUrl: "https://developers.openai.com/api/docs/models/gpt-6-sol",
      availabilityStatus: "available",
    }),
    createModel({
      id: "gpt-6-sol-long-context",
      providerId: "openai",
      name: "GPT-6 Sol · >272K input",
      description: "长上下文请求完整计价档",
      descriptionEn: "Full-request long-context pricing tier",
      currency: "USD",
      inputCostPer1mToken: 4,
      outputCostPer1mToken: 15,
      cacheReadCostPer1mToken: 0.4,
      cacheWriteCostPer1mToken: 5,
      pricingContext: "输入超过 272K tokens 时适用于整次请求",
      pricingContextEn: "Applies to the full request when input exceeds 272K tokens",
      pricingNote: "长上下文溢价适用于完整请求，不是只对超过门槛的 token 计价。",
      pricingNoteEn: "The long-context premium applies to the full request, not only tokens above the threshold.",
      sourceUrl: "https://developers.openai.com/api/docs/models/gpt-6-sol",
      availabilityStatus: "available",
    }),
    createModel({
      id: "gpt-6-luna",
      providerId: "openai",
      name: "GPT-6 Luna",
      description: "高吞吐轻量任务",
      descriptionEn: "Efficient model for focused, high-volume tasks",
      currency: "USD",
      inputCostPer1mToken: 0.1,
      outputCostPer1mToken: 0.5,
      cacheReadCostPer1mToken: 0.01,
      cacheWriteCostPer1mToken: 0.125,
      pricingContext: "标准档；输入不超过 272K tokens",
      pricingContextEn: "Standard tier; up to 272K input tokens",
      pricingNote: "输入超过 272K 时适用单列的整次请求长上下文价格：输入 $0.20、输出 $0.75、缓存读 $0.02、写 $0.25。",
      pricingNoteEn: "Over 272K input uses the separately listed full-request long-context rates: $0.20 input, $0.75 output, $0.02 cache read, and $0.25 cache write.",
      sourceUrl: "https://developers.openai.com/api/docs/models/gpt-6-luna",
      availabilityStatus: "available",
    }),
    createModel({
      id: "gpt-6-luna-long-context",
      providerId: "openai",
      name: "GPT-6 Luna · >272K input",
      description: "长上下文请求完整计价档",
      descriptionEn: "Full-request long-context pricing tier",
      currency: "USD",
      inputCostPer1mToken: 0.2,
      outputCostPer1mToken: 0.75,
      cacheReadCostPer1mToken: 0.02,
      cacheWriteCostPer1mToken: 0.25,
      pricingContext: "输入超过 272K tokens 时适用于整次请求",
      pricingContextEn: "Applies to the full request when input exceeds 272K tokens",
      pricingNote: "长上下文溢价适用于完整请求，不是只对超过门槛的 token 计价。",
      pricingNoteEn: "The long-context premium applies to the full request, not only tokens above the threshold.",
      sourceUrl: "https://developers.openai.com/api/docs/models/gpt-6-luna",
      availabilityStatus: "available",
    }),
    createModel({
      id: "gpt-5.5",
      providerId: "openai",
      name: "GPT-5.5",
      description: "仍提供的上一代旗舰模型",
      descriptionEn: "Available previous-generation flagship",
      currency: "USD",
      inputCostPer1mToken: 5,
      outputCostPer1mToken: 30,
      cacheReadCostPer1mToken: 0.5,
      pricingContext: "标准档；输入不超过 272K tokens（上一代）",
      pricingContextEn: "Standard tier; up to 272K input tokens (previous generation)",
      pricingNote: "官方模型页确认 API 支持；输入超过 272K 时使用单列的整次请求长上下文档。",
      pricingNoteEn: "The official model page confirms API support; over 272K input uses the separately listed full-request long-context tier.",
      sourceUrl: "https://developers.openai.com/api/docs/models/gpt-5.5",
      availabilityStatus: "available",
    }),
    createModel({
      id: "gpt-5.5-long-context",
      providerId: "openai",
      name: "GPT-5.5 · >272K input",
      description: "上一代模型长上下文完整计价档",
      descriptionEn: "Previous-generation full-request long-context tier",
      currency: "USD",
      inputCostPer1mToken: 10,
      outputCostPer1mToken: 45,
      cacheReadCostPer1mToken: 1,
      pricingContext: "输入超过 272K tokens 时适用于整次请求",
      pricingContextEn: "Applies to the full request when input exceeds 272K tokens",
      pricingNote: "官方模型页明确整次请求输入按 2 倍、输出按 1.5 倍计费。",
      pricingNoteEn: "The official model page applies 2x input and 1.5x output rates to the full request.",
      sourceUrl: "https://developers.openai.com/api/docs/models/gpt-5.5",
      availabilityStatus: "available",
    }),
    createModel({
      id: "gpt-5.4",
      providerId: "openai",
      name: "GPT-5.4",
      description: "仍提供的上一代编程模型",
      descriptionEn: "Available previous-generation coding model",
      currency: "USD",
      inputCostPer1mToken: 2.5,
      outputCostPer1mToken: 15,
      cacheReadCostPer1mToken: 0.25,
      pricingContext: "标准档；输入不超过 272K tokens（上一代）",
      pricingContextEn: "Standard tier; up to 272K input tokens (previous generation)",
      pricingNote: "输入超过 272K 时使用单列的整次请求长上下文价格；批处理、Flex 和 Fast 价格未计入。",
      pricingNoteEn: "Over 272K input uses the separately listed full-request long-context rates; Batch, Flex, and Fast rates are excluded.",
      sourceUrl: "https://developers.openai.com/api/docs/models/gpt-5.4",
      availabilityStatus: "available",
      legacyIds: ["gpt-5.4-2026-03-05"],
    }),
    createModel({
      id: "gpt-5.4-long-context",
      providerId: "openai",
      name: "GPT-5.4 · >272K input",
      description: "上一代模型长上下文完整计价档",
      descriptionEn: "Previous-generation full-request long-context tier",
      currency: "USD",
      inputCostPer1mToken: 5,
      outputCostPer1mToken: 22.5,
      cacheReadCostPer1mToken: 0.5,
      pricingContext: "输入超过 272K tokens 时适用于整次请求",
      pricingContextEn: "Applies to the full request when input exceeds 272K tokens",
      pricingNote: "官方模型页确认超过 272K 输入时整次请求输入按 2 倍、输出按 1.5 倍计费。",
      pricingNoteEn: "The official model page confirms 2x input and 1.5x output rates for the full request above 272K input tokens.",
      sourceUrl: "https://developers.openai.com/api/docs/models/gpt-5.4",
      availabilityStatus: "available",
    }),
    createModel({
      id: "gpt-5.4-mini",
      providerId: "openai",
      name: "GPT-5.4 mini",
      description: "上一代轻量编程模型",
      descriptionEn: "Previous-generation lightweight coding model",
      currency: "USD",
      inputCostPer1mToken: 0.75,
      outputCostPer1mToken: 4.5,
      cacheReadCostPer1mToken: 0.075,
      pricingContext: "标准价格；未列长上下文档",
      pricingContextEn: "Standard price; no long-context tier listed",
      pricingNote: "上一代型号；当前官方定价页仍列出。",
      pricingNoteEn: "Previous-generation model; still listed on the current official pricing page.",
      sourceUrl: openAiPricingUrl,
      availabilityStatus: "available",
    }),
    createModel({
      id: "gpt-5.4-nano",
      providerId: "openai",
      name: "GPT-5.4 nano",
      description: "上一代轻量批量任务模型",
      descriptionEn: "Previous-generation model for lightweight, high-volume tasks",
      currency: "USD",
      inputCostPer1mToken: 0.2,
      outputCostPer1mToken: 1.25,
      cacheReadCostPer1mToken: 0.02,
      pricingContext: "标准价格；未列长上下文档",
      pricingContextEn: "Standard price; no long-context tier listed",
      pricingNote: "上一代型号；当前官方定价页仍列出。",
      pricingNoteEn: "Previous-generation model; still listed on the current official pricing page.",
      sourceUrl: openAiPricingUrl,
      availabilityStatus: "available",
    }),
    createModel({
      id: "gpt-5",
      providerId: "openai",
      name: "GPT-5",
      description: "仍列于官方定价页的旧一代型号",
      descriptionEn: "Older-generation model still listed on official pricing",
      currency: "USD",
      inputCostPer1mToken: 1.25,
      outputCostPer1mToken: 10,
      cacheReadCostPer1mToken: 0.125,
      pricingContext: "旧一代标准价格",
      pricingContextEn: "Older-generation standard price",
      pricingNote: "历史 ID `gpt-5` 保留为此型号本身，不再误映射到 GPT-5.4。",
      pricingNoteEn: "The historical `gpt-5` ID remains this model; it no longer incorrectly maps to GPT-5.4.",
      sourceUrl: openAiPricingUrl,
      availabilityStatus: "available",
    }),
    createModel({
      id: "gpt-5-mini",
      providerId: "openai",
      name: "GPT-5 mini",
      description: "仍列于官方定价页的轻量旧一代型号",
      descriptionEn: "Lightweight older-generation model still listed on official pricing",
      currency: "USD",
      inputCostPer1mToken: 0.25,
      outputCostPer1mToken: 2,
      cacheReadCostPer1mToken: 0.025,
      pricingContext: "旧一代标准价格",
      pricingContextEn: "Older-generation standard price",
      pricingNote: "历史 ID `gpt-5-mini` 保留为此型号本身，不再误映射到 GPT-5.4 mini。",
      pricingNoteEn: "The historical `gpt-5-mini` ID remains this model; it no longer incorrectly maps to GPT-5.4 mini.",
      sourceUrl: openAiPricingUrl,
      availabilityStatus: "available",
    }),
    createModel({
      id: "gpt-5-nano",
      providerId: "openai",
      name: "GPT-5 nano",
      description: "仍列于官方定价页的轻量旧一代型号",
      descriptionEn: "Lightweight older-generation model still listed on official pricing",
      currency: "USD",
      inputCostPer1mToken: 0.05,
      outputCostPer1mToken: 0.4,
      cacheReadCostPer1mToken: 0.005,
      pricingContext: "旧一代标准价格",
      pricingContextEn: "Older-generation standard price",
      pricingNote: "旧一代型号；当前官方定价页仍列出。",
      pricingNoteEn: "Older-generation model; still listed on the current official pricing page.",
      sourceUrl: openAiPricingUrl,
      availabilityStatus: "available",
    }),
    createModel({
      id: "claude-fable-5-1",
      providerId: "anthropic",
      name: "Claude Fable 5.1",
      description: "复杂推理与长程智能体任务",
      descriptionEn: "Demanding reasoning and long-horizon agentic work",
      currency: "USD",
      inputCostPer1mToken: 10,
      outputCostPer1mToken: 50,
      cacheReadCostPer1mToken: 0.25,
      cacheWriteCostPer1mToken: 12.5,
      pricingContext: "Claude API 标准价；缓存写入字段为 5 分钟档",
      pricingContextEn: "Claude API standard; cache-write field is the 5-minute tier",
      pricingNote: "1 小时缓存写入为 $20/百万 tokens；读取为输入价格的 0.025 倍。",
      pricingNoteEn: "One-hour cache writes cost $20/MTok; cache reads cost 0.025x base input.",
      sourceUrl: "https://platform.claude.com/docs/en/models/fable-5-1/overview",
      availabilityStatus: "available",
    }),
    createModel({
      id: "claude-opus-5-5",
      providerId: "anthropic",
      name: "Claude Opus 5.5",
      description: "长程智能体编程与知识工作",
      descriptionEn: "Long-running agentic coding and knowledge work",
      currency: "USD",
      inputCostPer1mToken: 4,
      outputCostPer1mToken: 20,
      cacheReadCostPer1mToken: 0.2,
      cacheWriteCostPer1mToken: 5,
      pricingContext: "Claude API 标准价；缓存写入字段为 5 分钟档",
      pricingContextEn: "Claude API standard; cache-write field is the 5-minute tier",
      pricingNote: "1 小时缓存写入为 $8/百万 tokens；读取为输入价格的 0.05 倍。",
      pricingNoteEn: "One-hour cache writes cost $8/MTok; cache reads cost 0.05x base input.",
      sourceUrl: "https://platform.claude.com/docs/en/models/opus-5-5/overview",
      availabilityStatus: "available",
    }),
    createModel({
      id: "claude-sonnet-5",
      providerId: "anthropic",
      name: "Claude Sonnet 5",
      description: "速度与智能的均衡选择",
      descriptionEn: "A balance of speed and intelligence",
      currency: "USD",
      inputCostPer1mToken: 2,
      outputCostPer1mToken: 10,
      cacheReadCostPer1mToken: 0.2,
      cacheWriteCostPer1mToken: 2.5,
      pricingContext: "Claude API 标准价；缓存写入字段为 5 分钟档",
      pricingContextEn: "Claude API standard; cache-write field is the 5-minute tier",
      pricingNote: "1 小时缓存写入为 $4/百万 tokens。$2/$10 已是标准价格，未计入已取消的计划涨价。",
      pricingNoteEn: "$4/MTok for one-hour cache writes. $2/$10 is now standard; the announced increase was cancelled.",
      sourceUrl: "https://platform.claude.com/docs/en/models/sonnet-5/overview",
      availabilityStatus: "available",
    }),
    createModel({
      id: "claude-haiku-4-5",
      providerId: "anthropic",
      name: "Claude Haiku 4.5",
      description: "快速轻量模型",
      descriptionEn: "Fast, lightweight model",
      currency: "USD",
      inputCostPer1mToken: 1,
      outputCostPer1mToken: 5,
      cacheReadCostPer1mToken: 0.1,
      cacheWriteCostPer1mToken: 1.25,
      pricingContext: "Claude API 标准价；缓存写入字段为 5 分钟档",
      pricingContextEn: "Claude API standard; cache-write field is the 5-minute tier",
      pricingNote: "1 小时缓存写入为 $2/百万 tokens；API alias 为 `claude-haiku-4-5`。",
      pricingNoteEn: "One-hour cache writes cost $2/MTok; API alias is `claude-haiku-4-5`.",
      sourceUrl: "https://platform.claude.com/docs/en/models/haiku-4-5/overview",
      availabilityStatus: "available",
      legacyIds: ["claude-haiku-4-5-20251001"],
    }),
    createModel({
      id: "claude-opus-4-7",
      providerId: "anthropic",
      name: "Claude Opus 4.7",
      description: "仍可使用的上一代 Opus",
      descriptionEn: "Available legacy Opus model",
      currency: "USD",
      inputCostPer1mToken: 5,
      outputCostPer1mToken: 25,
      cacheReadCostPer1mToken: 0.5,
      cacheWriteCostPer1mToken: 6.25,
      pricingContext: "可用旧型号；缓存写入字段为 5 分钟档",
      pricingContextEn: "Available legacy model; cache-write field is the 5-minute tier",
      pricingNote: "1 小时缓存写入为 $10/百万 tokens；保留为独立旧型号，不映射到 Opus 5.5。",
      pricingNoteEn: "One-hour cache writes cost $10/MTok; retained as a distinct legacy model, not mapped to Opus 5.5.",
      sourceUrl: "https://platform.claude.com/docs/en/models/opus-4-7/overview",
      availabilityStatus: "available",
    }),
    createModel({
      id: "claude-opus-4-6",
      providerId: "anthropic",
      name: "Claude Opus 4.6",
      description: "仍可使用的上一代 Opus",
      descriptionEn: "Available legacy Opus model",
      currency: "USD",
      inputCostPer1mToken: 5,
      outputCostPer1mToken: 25,
      cacheReadCostPer1mToken: 0.5,
      cacheWriteCostPer1mToken: 6.25,
      pricingContext: "可用旧型号；缓存写入字段为 5 分钟档",
      pricingContextEn: "Available legacy model; cache-write field is the 5-minute tier",
      pricingNote: "1 小时缓存写入为 $10/百万 tokens；历史 ID 仍指向 Opus 4.6 本身。",
      pricingNoteEn: "One-hour cache writes cost $10/MTok; the historical ID continues to identify Opus 4.6 itself.",
      sourceUrl: anthropicPricingUrl,
      availabilityStatus: "available",
    }),
    createModel({
      id: "claude-sonnet-4-6",
      providerId: "anthropic",
      name: "Claude Sonnet 4.6",
      description: "仍可使用的上一代 Sonnet",
      descriptionEn: "Available legacy Sonnet model",
      currency: "USD",
      inputCostPer1mToken: 3,
      outputCostPer1mToken: 15,
      cacheReadCostPer1mToken: 0.3,
      cacheWriteCostPer1mToken: 3.75,
      pricingContext: "可用旧型号；缓存写入字段为 5 分钟档",
      pricingContextEn: "Available legacy model; cache-write field is the 5-minute tier",
      pricingNote: "1 小时缓存写入为 $6/百万 tokens；独立保留，不映射到 Sonnet 5。",
      pricingNoteEn: "One-hour cache writes cost $6/MTok; retained separately and not mapped to Sonnet 5.",
      sourceUrl: "https://platform.claude.com/docs/en/models/sonnet-4-6/overview",
      availabilityStatus: "available",
    }),
    createModel({
      id: "deepseek-flash",
      providerId: "deepseek",
      name: "DeepSeek-V4.1-Flash",
      description: "Off-peak、缓存未命中",
      descriptionEn: "Off-peak, cache miss",
      currency: "USD",
      inputCostPer1mToken: 0.15,
      outputCostPer1mToken: 0.6,
      cacheReadCostPer1mToken: 0.003,
      pricingContext: "非高峰时段 00:00-01:00、04:00-06:00、10:00-24:00 UTC；未命中缓存",
      pricingContextEn: "Off-peak 00:00-01:00, 04:00-06:00, and 10:00-24:00 UTC; cache miss",
      pricingNote: "周一至周五 01:00-04:00、06:00-10:00 UTC（中国法定节假日除外）为峰值档；缓存命中行单列。历史 ID `deepseek-v4-flash` 与 `deepseek-v4-flash-vision-exp` 仍由官方路由至此模型；`deepseek-chat` 和 `deepseek-reasoner` 未确认等价路由。",
      pricingNoteEn: "Peak is 01:00-04:00 and 06:00-10:00 UTC Monday-Friday, excluding Chinese public holidays; cache-hit rows are listed separately. The provider confirms legacy IDs `deepseek-v4-flash` and `deepseek-v4-flash-vision-exp` route here; equivalence for `deepseek-chat` and `deepseek-reasoner` is unverified.",
      sourceUrl: deepSeekPricingUrl,
      availabilityStatus: "available",
      legacyIds: ["deepseek-v4-flash", "deepseek-v4-flash-vision-exp"],
    }),
    createModel({
      id: "deepseek-flash-peak",
      providerId: "deepseek",
      name: "DeepSeek-V4.1-Flash",
      description: "Peak、缓存未命中",
      descriptionEn: "Peak, cache miss",
      currency: "USD",
      inputCostPer1mToken: 0.3,
      outputCostPer1mToken: 1.2,
      cacheReadCostPer1mToken: 0.006,
      pricingContext: "周一至周五 01:00-04:00、06:00-10:00 UTC；中国法定节假日除外",
      pricingContextEn: "Monday-Friday, 01:00-04:00 and 06:00-10:00 UTC; excluding Chinese public holidays",
      pricingNote: "峰值时段缓存未命中价格；缓存命中输入价为 $0.006/百万 tokens。",
      pricingNoteEn: "Peak cache-miss tier; cache-hit input is $0.006/MTok.",
      sourceUrl: deepSeekPricingUrl,
      availabilityStatus: "available",
    }),
    createModel({
      id: "deepseek-flash-cache-hit",
      providerId: "deepseek",
      name: "DeepSeek-V4.1-Flash",
      description: "Off-peak、缓存命中",
      descriptionEn: "Off-peak, cache hit",
      currency: "USD",
      inputCostPer1mToken: 0.003,
      outputCostPer1mToken: 0.6,
      cacheReadCostPer1mToken: 0.003,
      pricingContext: "仅缓存实际命中时适用；非高峰时段",
      pricingContextEn: "Only applies when cache is actually hit; off-peak",
      pricingNote: "自动缓存命中不保证；未命中部分按 $0.15 输入/百万 tokens 另计。",
      pricingNoteEn: "Automatic cache hits are not guaranteed; cache misses are billed separately at $0.15 input/MTok.",
      sourceUrl: deepSeekPricingUrl,
      availabilityStatus: "available",
    }),
    createModel({
      id: "deepseek-flash-peak-cache-hit",
      providerId: "deepseek",
      name: "DeepSeek-V4.1-Flash",
      description: "Peak、缓存命中",
      descriptionEn: "Peak, cache hit",
      currency: "USD",
      inputCostPer1mToken: 0.006,
      outputCostPer1mToken: 1.2,
      cacheReadCostPer1mToken: 0.006,
      pricingContext: "仅缓存实际命中时适用；工作日峰值时段",
      pricingContextEn: "Only applies when cache is actually hit; weekday peak hours",
      pricingNote: "自动缓存命中不保证；未命中部分按 $0.30 输入/百万 tokens 另计。",
      pricingNoteEn: "Automatic cache hits are not guaranteed; cache misses are billed separately at $0.30 input/MTok.",
      sourceUrl: deepSeekPricingUrl,
      availabilityStatus: "available",
    }),
    createModel({
      id: "deepseek-v4-pro",
      providerId: "deepseek",
      name: "DeepSeek-V4-Pro-0813",
      description: "Off-peak、缓存未命中",
      descriptionEn: "Off-peak, cache miss",
      currency: "USD",
      inputCostPer1mToken: 0.66,
      outputCostPer1mToken: 1.98,
      cacheReadCostPer1mToken: 0.022,
      pricingContext: "非高峰时段；缓存未命中",
      pricingContextEn: "Off-peak; cache miss",
      pricingNote: "非高峰包括周末及中国法定节假日；历史 `deepseek-r1` / `deepseek-reasoner` 路由未确认，不做等价映射。",
      pricingNoteEn: "Off-peak includes weekends and Chinese public holidays; routing for historical `deepseek-r1` / `deepseek-reasoner` IDs is unverified and is not mapped.",
      sourceUrl: deepSeekPricingUrl,
      availabilityStatus: "available",
    }),
    createModel({
      id: "deepseek-v4-pro-peak",
      providerId: "deepseek",
      name: "DeepSeek-V4-Pro-0813",
      description: "Peak、缓存未命中",
      descriptionEn: "Peak, cache miss",
      currency: "USD",
      inputCostPer1mToken: 1.32,
      outputCostPer1mToken: 3.96,
      cacheReadCostPer1mToken: 0.044,
      pricingContext: "周一至周五 01:00-04:00、06:00-10:00 UTC；中国法定节假日除外",
      pricingContextEn: "Monday-Friday, 01:00-04:00 and 06:00-10:00 UTC; excluding Chinese public holidays",
      pricingNote: "峰值时段缓存未命中价格；缓存命中输入价为 $0.044/百万 tokens。",
      pricingNoteEn: "Peak cache-miss tier; cache-hit input is $0.044/MTok.",
      sourceUrl: deepSeekPricingUrl,
      availabilityStatus: "available",
    }),
    createModel({
      id: "deepseek-v4-pro-cache-hit",
      providerId: "deepseek",
      name: "DeepSeek-V4-Pro-0813",
      description: "Off-peak、缓存命中",
      descriptionEn: "Off-peak, cache hit",
      currency: "USD",
      inputCostPer1mToken: 0.022,
      outputCostPer1mToken: 1.98,
      cacheReadCostPer1mToken: 0.022,
      pricingContext: "仅缓存实际命中时适用；非高峰时段",
      pricingContextEn: "Only applies when cache is actually hit; off-peak",
      pricingNote: "自动缓存命中不保证；未命中部分按 $0.66 输入/百万 tokens 另计。",
      pricingNoteEn: "Automatic cache hits are not guaranteed; cache misses are billed separately at $0.66 input/MTok.",
      sourceUrl: deepSeekPricingUrl,
      availabilityStatus: "available",
    }),
    createModel({
      id: "deepseek-v4-pro-peak-cache-hit",
      providerId: "deepseek",
      name: "DeepSeek-V4-Pro-0813",
      description: "Peak、缓存命中",
      descriptionEn: "Peak, cache hit",
      currency: "USD",
      inputCostPer1mToken: 0.044,
      outputCostPer1mToken: 3.96,
      cacheReadCostPer1mToken: 0.044,
      pricingContext: "仅缓存实际命中时适用；工作日峰值时段",
      pricingContextEn: "Only applies when cache is actually hit; weekday peak hours",
      pricingNote: "自动缓存命中不保证；未命中部分按 $1.32 输入/百万 tokens 另计。",
      pricingNoteEn: "Automatic cache hits are not guaranteed; cache misses are billed separately at $1.32 input/MTok.",
      sourceUrl: deepSeekPricingUrl,
      availabilityStatus: "available",
    }),
    createModel({
      id: "glm-5.3",
      providerId: "glm",
      name: "GLM-5.3",
      description: "旗舰编程与智能体模型",
      descriptionEn: "Flagship coding and agentic model",
      currency: "CNY",
      inputCostPer1mToken: 8,
      outputCostPer1mToken: 28,
      cacheReadCostPer1mToken: 2,
      pricingContext: "中国 BigModel API 标准档",
      pricingContextEn: "Chinese BigModel API standard tier",
      pricingNote: "缓存命中 ¥2/百万 tokens；缓存存储当前限时免费。",
      pricingNoteEn: "Cache reads cost CNY 2/MTok; cache storage is currently temporarily free.",
      sourceUrl: bigModelPricingUrl,
      availabilityStatus: "available",
    }),
    createModel({
      id: "glm-5.3-flash",
      providerId: "glm",
      name: "GLM-5.3-Flash",
      description: "高性价比多模态模型",
      descriptionEn: "Cost-efficient multimodal model",
      currency: "CNY",
      inputCostPer1mToken: 0.8,
      outputCostPer1mToken: 2.8,
      cacheReadCostPer1mToken: 0.23,
      pricingContext: "中国 BigModel API 标准档",
      pricingContextEn: "Chinese BigModel API standard tier",
      pricingNote: "缓存命中 ¥0.23/百万 tokens；缓存存储当前限时免费。",
      pricingNoteEn: "Cache reads cost CNY 0.23/MTok; cache storage is currently temporarily free.",
      sourceUrl: bigModelOverviewUrl,
      availabilityStatus: "available",
    }),
    createModel({
      id: "glm-5.3-flashx",
      providerId: "glm",
      name: "GLM-5.3-FlashX",
      description: "高速 GLM-5.3-Flash",
      descriptionEn: "Faster GLM-5.3-Flash",
      currency: "CNY",
      inputCostPer1mToken: 2,
      outputCostPer1mToken: 7,
      cacheReadCostPer1mToken: 0.57,
      pricingContext: "中国 BigModel API 标准档",
      pricingContextEn: "Chinese BigModel API standard tier",
      pricingNote: "缓存命中 ¥0.57/百万 tokens；缓存存储当前限时免费。",
      pricingNoteEn: "Cache reads cost CNY 0.57/MTok; cache storage is currently temporarily free.",
      sourceUrl: bigModelPricingUrl,
      availabilityStatus: "available",
    }),
    createModel({
      id: "glm-5-turbo-base",
      providerId: "glm",
      name: "GLM-5-Turbo",
      description: "仍在售的上一代长流程模型",
      descriptionEn: "Available previous-generation long-workflow model",
      currency: "CNY",
      inputCostPer1mToken: 5,
      outputCostPer1mToken: 22,
      cacheReadCostPer1mToken: 1.2,
      pricingContext: "输入 [0, 32K)；中国 BigModel CNY",
      pricingContextEn: "Input [0, 32K); Chinese BigModel CNY",
      pricingNote: "输入 ≥32K 档为 ¥7 / ¥26；缓存命中分别 ¥1.2 / ¥1.8；缓存存储限时免费。",
      pricingNoteEn: "Input ≥32K tier is CNY 7 / 26; cache reads are CNY 1.2 / 1.8 respectively; cache storage is temporarily free.",
      sourceUrl: bigModelPricingUrl,
      availabilityStatus: "available",
    }),
    createModel({
      id: "glm-5-base",
      providerId: "glm",
      name: "GLM-5",
      description: "仍在售的上一代通用推理模型",
      descriptionEn: "Available previous-generation general reasoning model",
      currency: "CNY",
      inputCostPer1mToken: 4,
      outputCostPer1mToken: 18,
      cacheReadCostPer1mToken: 1,
      pricingContext: "输入 [0, 32K)；中国 BigModel CNY",
      pricingContextEn: "Input [0, 32K); Chinese BigModel CNY",
      pricingNote: "输入 ≥32K 档为 ¥6 / ¥22；缓存命中分别 ¥1 / ¥1.5；缓存存储限时免费。",
      pricingNoteEn: "Input ≥32K tier is CNY 6 / 22; cache reads are CNY 1 / 1.5 respectively; cache storage is temporarily free.",
      sourceUrl: bigModelPricingUrl,
      availabilityStatus: "available",
    }),
    createModel({
      id: "glm-4-7-base",
      providerId: "glm",
      name: "GLM-4.7",
      description: "仍在售的上一代通用文本模型",
      descriptionEn: "Available previous-generation general text model",
      currency: "CNY",
      inputCostPer1mToken: 2,
      outputCostPer1mToken: 8,
      cacheReadCostPer1mToken: 0.4,
      pricingContext: "输入 [0, 32K)，输出 [0, 0.2K)；中国 BigModel CNY",
      pricingContextEn: "Input [0, 32K), output [0, 0.2K); Chinese BigModel CNY",
      pricingNote: "输出 ≥0.2K 的对应档为 ¥3 / ¥14；输入 [32K, 200K) 档为 ¥4 / ¥16，缓存命中分别为 ¥0.6 和 ¥0.8；存储限时免费。",
      pricingNoteEn: "The output ≥0.2K tier is CNY 3 / 14; input [32K, 200K) is CNY 4 / 16, with cache reads CNY 0.6 and 0.8 respectively; storage is temporarily free.",
      sourceUrl: bigModelPricingUrl,
      availabilityStatus: "available",
    }),
    createModel({
      id: "MiniMax-M3",
      providerId: "minimax",
      name: "MiniMax-M3",
      description: "标准 PAYG，输入不超过 512K",
      descriptionEn: "Standard PAYG; up to 512K input",
      currency: "USD",
      inputCostPer1mToken: 0.3,
      outputCostPer1mToken: 1.2,
      cacheReadCostPer1mToken: 0.06,
      pricingContext: "≤512K 输入；标准服务档",
      pricingContextEn: "≤512K input; standard service tier",
      pricingNote: "当前显示价包含永久 50% 折扣；优先级档为 1.5 倍。PAYG 表未列缓存写入价格。",
      pricingNoteEn: "Displayed rates include the published permanent 50% discount; Priority is 1.5x. The PAYG table does not list a cache-write rate.",
      sourceUrl: miniMaxPricingUrl,
      availabilityStatus: "available",
    }),
    createModel({
      id: "MiniMax-M3-over-512k",
      providerId: "minimax",
      name: "MiniMax-M3 · >512K input",
      description: "标准 PAYG 长输入档",
      descriptionEn: "Standard PAYG long-input tier",
      currency: "USD",
      inputCostPer1mToken: 0.6,
      outputCostPer1mToken: 2.4,
      cacheReadCostPer1mToken: 0.12,
      pricingContext: "输入超过 512K；标准服务档",
      pricingContextEn: "Input exceeds 512K; standard service tier",
      pricingNote: "当前显示价包含永久 50% 折扣；本档适用于长输入请求。PAYG 表未列缓存写入价格。",
      pricingNoteEn: "Displayed rates include the published permanent 50% discount; this tier applies to long-input requests. The PAYG table does not list a cache-write rate.",
      sourceUrl: miniMaxPricingUrl,
      availabilityStatus: "available",
    }),
    createModel({
      id: "MiniMax-M2.7",
      providerId: "minimax",
      name: "MiniMax-M2.7",
      description: "通用代码与智能体任务",
      descriptionEn: "General coding and agent work",
      currency: "USD",
      inputCostPer1mToken: 0.3,
      outputCostPer1mToken: 1.2,
      cacheReadCostPer1mToken: 0.06,
      cacheWriteCostPer1mToken: 0.375,
      pricingContext: "标准 PAYG；显式缓存写入与被动缓存写入分别计价",
      pricingContextEn: "Standard PAYG; explicit and passive cache writes differ",
      pricingNote: "显式缓存写入 $0.375/百万 tokens；被动缓存写入不额外收费。",
      pricingNoteEn: "Explicit cache writes cost $0.375/MTok; passive cache writes have no additional charge.",
      sourceUrl: miniMaxPricingUrl,
      availabilityStatus: "available",
    }),
    createModel({
      id: "MiniMax-M2.7-highspeed",
      providerId: "minimax",
      name: "MiniMax-M2.7-highspeed",
      description: "高吞吐快速响应型号",
      descriptionEn: "High-throughput, faster-response model",
      currency: "USD",
      inputCostPer1mToken: 0.6,
      outputCostPer1mToken: 2.4,
      cacheReadCostPer1mToken: 0.06,
      cacheWriteCostPer1mToken: 0.375,
      pricingContext: "标准 PAYG；显式缓存写入与被动缓存写入分别计价",
      pricingContextEn: "Standard PAYG; explicit and passive cache writes differ",
      pricingNote: "PAYG 定价页列输入 $0.60；Anthropic 兼容缓存指南列 $0.30，官方文档相互矛盾。此处暂按 PAYG 表列价，不能视为确定的发票费率。显式写入 $0.375；被动写入不额外收费。",
      pricingNoteEn: "The PAYG page lists $0.60 input, while the Anthropic-compatible cache guide lists $0.30; the official pages conflict. This snapshot provisionally follows PAYG and is not a definitive invoice rate. Explicit writes cost $0.375; passive writes have no additional charge.",
      sourceUrl: miniMaxPricingUrl,
      availabilityStatus: "available",
    }),
    createModel({
      id: "MiniMax-M2.5",
      providerId: "minimax",
      name: "MiniMax-M2.5",
      description: "仍列于 PAYG 的上一代型号",
      descriptionEn: "Previous-generation model still listed in PAYG",
      currency: "USD",
      inputCostPer1mToken: 0.3,
      outputCostPer1mToken: 1.2,
      cacheReadCostPer1mToken: 0.03,
      cacheWriteCostPer1mToken: 0.375,
      pricingContext: "标准 PAYG 旧型号；显式缓存写入",
      pricingContextEn: "Standard PAYG legacy model; explicit cache writes",
      pricingNote: "历史网站 ID `minimax-m2-5` 正确指向 M2.5，而不是显示成 M2.7。",
      pricingNoteEn: "Historical site ID `minimax-m2-5` correctly identifies M2.5 rather than displaying as M2.7.",
      sourceUrl: miniMaxPricingUrl,
      availabilityStatus: "available",
      legacyIds: ["minimax-m2-5"],
    }),
    createModel({
      id: "MiniMax-M2.5-highspeed",
      providerId: "minimax",
      name: "MiniMax-M2.5-highspeed",
      description: "仍列于 PAYG 的上一代高速型号",
      descriptionEn: "Previous-generation high-speed model still listed in PAYG",
      currency: "USD",
      inputCostPer1mToken: 0.6,
      outputCostPer1mToken: 2.4,
      cacheReadCostPer1mToken: 0.03,
      cacheWriteCostPer1mToken: 0.375,
      pricingContext: "标准 PAYG 旧型号；显式缓存写入",
      pricingContextEn: "Standard PAYG legacy model; explicit cache writes",
      pricingNote: "历史网站 ID `minimax-m2-5-highspeed` 正确指向 M2.5-highspeed，而不是显示成 M2.7-highspeed。",
      pricingNoteEn: "Historical site ID `minimax-m2-5-highspeed` correctly identifies M2.5-highspeed rather than displaying as M2.7-highspeed.",
      sourceUrl: miniMaxPricingUrl,
      availabilityStatus: "available",
      legacyIds: ["minimax-m2-5-highspeed"],
    }),
  ],
}

export function getLocalizedModelCopy(
  model: Pick<
    ModelPricing,
    | "description"
    | "descriptionEn"
    | "pricingContext"
    | "pricingContextEn"
    | "pricingNote"
    | "pricingNoteEn"
    | "sourceLabel"
    | "sourceLabelEn"
    | "sourceNote"
    | "sourceNoteEn"
  >,
  language: SupportedLanguage,
) {
  return {
    description: language === "zh-CN" ? model.description : model.descriptionEn,
    pricingContext: language === "zh-CN" ? model.pricingContext : model.pricingContextEn,
    pricingNote: language === "zh-CN" ? model.pricingNote : model.pricingNoteEn,
    sourceLabel: language === "zh-CN" ? model.sourceLabel : model.sourceLabelEn,
    sourceNote: language === "zh-CN" ? model.sourceNote : model.sourceNoteEn,
  }
}

export function getProviderById(providerId: string) {
  return pricingData.providers.find((provider) => provider.id === providerId)
}

export function getLocalizedProviderCopy(
  provider: Pick<PricingProvider, "sourceLabel" | "sourceLabelEn" | "sourceNote" | "sourceNoteEn">,
  language: SupportedLanguage,
) {
  return {
    sourceLabel: language === "zh-CN" ? provider.sourceLabel : provider.sourceLabelEn,
    sourceNote: language === "zh-CN" ? provider.sourceNote : provider.sourceNoteEn,
  }
}

export function getLocalizedPricingSource(language: SupportedLanguage) {
  return language === "zh-CN" ? pricingData.source : pricingData.sourceEn
}

export function resolveCanonicalModelId(modelId: string | null | undefined): string | null {
  if (!modelId) return null

  const normalizedModelId = modelId.trim()
  const directModel = pricingData.models.find((model) => model.id === normalizedModelId)
  if (directModel) return directModel.id

  const legacyModel = pricingData.models.find((model) => model.legacyIds?.includes(normalizedModelId))
  return legacyModel?.id ?? null
}

export function getModelById(modelId: string) {
  const canonicalModelId = resolveCanonicalModelId(modelId)
  const model = pricingData.models.find((item) => item.id === canonicalModelId)
  if (!model) {
    throw new RangeError(`Unsupported pricing model ID: ${modelId}`)
  }
  return model
}
